### ISSUE TITLE
'None' to '0'

### ISSUE THREAD

**Issue by pcleddy** [datacratic/check_graphite#1] opened 2012-02-17 15:58 UTC
Does it makes sense that I had to convert 'None' values to '0'? Works now.

for i, v in enumerate(values):
    if (v == 'None'):
      values[i] = '0'

**Comment by pleddy** [comment] 2012-02-20 14:10
Better:

outlist=[]
for i, v in enumerate(values):
    if (v != 'None'):
      outlist.append(v)
values = outlist

**Comment by pleddy** [comment] 2012-02-24 08:24
outlist=[]
for i, v in enumerate(values):
    if (v != 'None'):
      outlist.append(v)

if outlist:
  values = outlist
else:
  graphite.unknown_error('only None data')

**Comment by nicolaskruchten** [comment] 2012-02-24 15:36
Sorry for the long silence on this. Turns out I patched our production version and never committed it! I've pushed the change we've been using for a while, it's a one-liner.

**Closed as completed by nicolaskruchten** 2012-02-24 15:36 UTC

**Comment by pleddy** [comment] 2012-02-24 15:48
Right, the problem is, if they are all 'None' then UNKNOWN is the better answer, otherwise, a load of "1.0" might be misleading. Just saying, not a big deal.

**Comment by nicolaskruchten** [comment] 2012-02-24 15:56
Fair enough. For our purposes, 'None' is equivalent to 0, as we're mostly just counting things.
